"""init schema

Revision ID: 4ed5e1310708
Revises: 
Create Date: 2026-03-22 17:51:51.843024
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '4ed5e1310708'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('forty_two_user_id', sa.BigInteger(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_forty_two_user_id'), 'users', ['forty_two_user_id'], unique=True)
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=False)
    op.create_table('app_refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_refresh_tokens_token_hash'), 'app_refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_app_refresh_tokens_user_id'), 'app_refresh_tokens', ['user_id'], unique=False)
    op.create_table('attendance_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('source_value_raw', sa.String(length=32), nullable=True),
    sa.Column('updated_from_source_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_attendance_daily_user_day')
    )
    op.create_index(op.f('ix_attendance_daily_day'), 'attendance_daily', ['day'], unique=False)
    op.create_index(op.f('ix_attendance_daily_user_id'), 'attendance_daily', ['user_id'], unique=False)
    op.create_table('attendance_sync_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_sync_runs_user_id'), 'attendance_sync_runs', ['user_id'], unique=False)
    op.create_table('deadlines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('target_hours', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadlines_user_id'), 'deadlines', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_goal_seconds', sa.Integer(), nullable=False),
    sa.Column('weekly_goal_seconds', sa.Integer(), nullable=False),
    sa.Column('monthly_goal_seconds', sa.Integer(), nullable=False),
    sa.Column('pace_mode', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_deadlines_user_id'), table_name='deadlines')
    op.drop_table('deadlines')
    op.drop_index(op.f('ix_attendance_sync_runs_user_id'), table_name='attendance_sync_runs')
    op.drop_table('attendance_sync_runs')
    op.drop_index(op.f('ix_attendance_daily_user_id'), table_name='attendance_daily')
    op.drop_index(op.f('ix_attendance_daily_day'), table_name='attendance_daily')
    op.drop_table('attendance_daily')
    op.drop_index(op.f('ix_app_refresh_tokens_user_id'), table_name='app_refresh_tokens')
    op.drop_index(op.f('ix_app_refresh_tokens_token_hash'), table_name='app_refresh_tokens')
    op.drop_table('app_refresh_tokens')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_index(op.f('ix_users_forty_two_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
